In [115]:
import numpy as np

In [116]:
np.array([2,4,56,78,556]) # 1D array

array([  2,   4,  56,  78, 556])

In [117]:
vector = np.array([2,4,56,422,32,1])    # vector
print(vector)

[  2   4  56 422  32   1]


In [118]:
type(vector)

numpy.ndarray

In [119]:
new = np.array([[45,34,22,2],
                [24,55,3,22]])
print(new[0][1])

34


In [120]:
# 3 D array   

np.array([[2,3,44,55],[23,4,5,77],[33,44,55,66],[44,44,55,66]])

array([[ 2,  3, 44, 55],
       [23,  4,  5, 77],
       [33, 44, 55, 66],
       [44, 44, 55, 66]])

# dtype

In [121]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)

int64


In [122]:
np.array([11,23,44], dtype = float)

array([11., 23., 44.])

In [123]:
np.array([11,23,44] , dtype = bool)

array([ True,  True,  True])

In [124]:
np.array([11,23,44], dtype = complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

# arange

In [125]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [126]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [127]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# reshape

In [129]:
np.arange(1,11).reshape(5,2) # converted 5 rows 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [130]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [131]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# one and zeros

In [132]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [133]:
np.ones((3,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [134]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [135]:
np.zeros((3,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# random

In [136]:
arr = np.random.randn(2, 3)
print(arr)

[[-0.53709977  0.46702436 -1.46452617]
 [ 1.67458724 -1.46482707  1.4773766 ]]


In [137]:
np.random.random((3,2))

array([[0.54110929, 0.75775412],
       [0.78583849, 0.55055795],
       [0.78404366, 0.31220647]])

In [138]:
np.random.randint(1, 10,(2, 3))

array([[8, 3, 1],
       [9, 5, 5]], dtype=int32)

In [139]:
np.random.rand(5)

array([0.00216564, 0.08347623, 0.82336302, 0.43801474, 0.26359293])

In [140]:
np.random.rand(2,4)

array([[0.68492552, 0.37167855, 0.05835584, 0.94610914],
       [0.30967391, 0.04684251, 0.17762428, 0.69353597]])

In [141]:
np.random.randint(2,4)

3

In [142]:
np.random.randint(2,29) # 2nd argument is exlusive

17

In [143]:
np.random.randint(0,1)

0

# linspace 

# '''It is also called as Linearly space , Linearly separable,in a given range at equal distance it creates points.'''

In [144]:
np.linspace(-10,20,50) #here : lower range ,upper rang , number of items to 

array([-10.        ,  -9.3877551 ,  -8.7755102 ,  -8.16326531,
        -7.55102041,  -6.93877551,  -6.32653061,  -5.71428571,
        -5.10204082,  -4.48979592,  -3.87755102,  -3.26530612,
        -2.65306122,  -2.04081633,  -1.42857143,  -0.81632653,
        -0.20408163,   0.40816327,   1.02040816,   1.63265306,
         2.24489796,   2.85714286,   3.46938776,   4.08163265,
         4.69387755,   5.30612245,   5.91836735,   6.53061224,
         7.14285714,   7.75510204,   8.36734694,   8.97959184,
         9.59183673,  10.20408163,  10.81632653,  11.42857143,
        12.04081633,  12.65306122,  13.26530612,  13.87755102,
        14.48979592,  15.10204082,  15.71428571,  16.32653061,
        16.93877551,  17.55102041,  18.16326531,  18.7755102 ,
        19.3877551 ,  20.        ])

In [145]:
np.linspace(-10,20,4)

array([-10.,   0.,  10.,  20.])

In [146]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

In [147]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

# identity matrix

In [148]:
# creating the identity matrix

np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [149]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [150]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [151]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Array Attribute

In [152]:
a1 = np.arange(10) # 1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
a2 = np.arange(12, dtype = float).reshape(3,4)  # Matrix
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [154]:
a3 = np.arange(8).reshape(2,2,2)  # 3D  --> Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim

In [155]:
a1.ndim   # 1 dimension array

1

In [156]:
a2.ndim  # 2 dimension array

2

In [157]:
a3.ndim  # 3 dimension array

3

# shape

In [158]:
arr = np.array([1, 2, 3])
print(arr.shape) 

(3,)


In [159]:
arr = np.array([[1, 2], [3, 4]])
print(arr.shape)

(2, 2)


In [160]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr.shape)

(2, 2, 2)


# size
give number of atom

In [161]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.size)  


4


In [162]:
arr = np.array([[1, 2], [3, 4]])
print(arr.size)

4


In [163]:
arr = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr.size)

8


# item size

# memory occupied by the item

In [164]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
a1.itemsize # bytes

8

In [166]:
a1.itemsize #bytes

8

In [167]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [168]:
a2.itemsize

8

In [169]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [170]:
a3.itemsize

8

# dtype

gives data type of item

In [171]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


# Changing data type

In [172]:
#astype

x = np.array([33,22,2.5])
print(x)

[33.  22.   2.5]


In [173]:
x.astype(int)

array([33, 22,  2])

# Array oprations

In [174]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)

In [175]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
z2 

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Scalar opration

Scalar oprations on numpy arrays include performing addition or substraction, or manupulation on each element of a numpy array

In [177]:
# arithmetic
z1 + 2      # it addition 2 to each element of z1


array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [178]:
# multiplication
z1 - 2   # it substract 2 from each eement of z1

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [179]:
# multiplication
z1 * 2  # it multiply each element of z1 by 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [180]:
# power
z1 ** 2 # it raise each element of z1 to the power of 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [181]:
# modulo
z1 % 2  # it gives the remainder of each elment of z1 when divided by 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

# relational Operators

`matchthe relational oprators are also known as comparison oprators the main function
is to return either a true or false on the value of operands

In [182]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [183]:
z2 > 2 # if 2 is greater than each element of z2 it returns True or False

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [184]:
z2 >20 

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

# vector opration

We can apply on both numpy arraym

In [185]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [187]:
# Arthematic
z1 + z2  # it add each element of z1 with each element of z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [188]:
z1 * z2  # it multiply each element of z1 with each element of z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [189]:
z1 - z2 # it subtract each element of z2 from each element of z1

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [190]:
z1 / z2  # it divide each element of z1 by each element of z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array Functions

In [191]:
k1 = np.random.random((3,3))
k1= np.round(k1*100) # rounding the values to nearest integer
k1 

array([[81.,  2., 78.],
       [27., 86., 72.],
       [65., 30.,  7.]])

In [192]:
# Max
np.max(k1)

np.float64(86.0)

In [193]:
# Min
np.min(k1)


np.float64(2.0)

In [ ]:
np.sum(k1) 

np.float64(448.0)

In [195]:
# prodduct ----> multiplication
np.prod(k1)  # it mulyiply each element of k1
# it gives the product of all element of k1

np.float64(28836130377600.0)

In Numpy

In [196]:
# if we want maximum of every row

np.max(k1 , axis= 1) # it shows maximum of every rows

array([81., 86., 65.])

In [197]:
# maximum of every column
np.max(k1, axis = 0) # it shows the maximum of every column

array([81., 86., 78.])

In [198]:
k2 = np.array([[48,90,67],[58,67,39],[80,70,57]])
print(k2)

[[48 90 67]
 [58 67 39]
 [80 70 57]]


In [199]:
np.max(k2, axis = 0)

array([80, 90, 67])

In [200]:
np.max(k2, axis = 1)

array([90, 67, 80])

statistics related

In [201]:
# means
k1

array([[81.,  2., 78.],
       [27., 86., 72.],
       [65., 30.,  7.]])

In [202]:
np.mean(k1) # it gives the mean oaf all elements of k1

np.float64(49.77777777777778)

In [203]:
k1.mean(axis=0)  # firstly it do addition 3 number and then it divide by
                 # 3 then it give the  answer that answer is mean of tht column



array([57.66666667, 39.33333333, 52.33333333])

In [204]:
# median 
np.median(k1)   # it gives the median of all element of k1

np.float64(65.0)

In [205]:
np.sort(k1, axis=1) #it sort arry in row wise

array([[ 2., 78., 81.],
       [27., 72., 86.],
       [ 7., 30., 65.]])

In [206]:
np.sort(k1, axis=0) # it sort array in column wise

array([[27.,  2.,  7.],
       [65., 30., 72.],
       [81., 86., 78.]])

In [207]:
k1

array([[81.,  2., 78.],
       [27., 86., 72.],
       [65., 30.,  7.]])

In [208]:
# standard deviation
np.std(k1) # it add  all the element of k1 and then it divide by number of element
        # then it take the 

np.float64(31.325452121514285)

In [209]:
np.std(k1, axis =0)

array([22.64705034, 34.92213561, 32.14895886])

In [210]:
# variance
np.var(k1) 

np.float64(981.2839506172838)

Trignometric functions

In [211]:
np.sin(k1)  # it give the sine of the each element of k1

array([[-0.62988799,  0.90929743,  0.51397846],
       [ 0.95637593, -0.92345845,  0.25382336],
       [ 0.82682868, -0.98803162,  0.6569866 ]])

In [212]:
np.cos(k1)  # it give the cosine of the each element of k1

array([[ 0.77668598, -0.41614684, -0.85780309],
       [-0.29213881, -0.38369844, -0.96725059],
       [-0.56245385,  0.15425145,  0.75390225]])

In [213]:
np.tan(k1)  # it give the tangent of the each elemrnt of k1

array([[-0.81099442, -2.18503986, -0.59918   ],
       [-3.2737038 ,  2.40672971, -0.26241738],
       [-1.47003826, -6.4053312 ,  0.87144798]])

 dot product

the numpy module of python  provide a function to  perform the dot product of two arrys

In [224]:
s2 = np.arange(12).reshape(3,4)   # it create a 3*4 matrix
s3 = np.arange(12,24).reshape(4,3) # it create 3*4 matrix

In [215]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [225]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
np.dot(s2,s3)   # this program not run because this s2 and s3 is 3*3 matrix 3*3 matrix arn't run


ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [218]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [221]:
np.dot(s2,s3.reshape(4,3))

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [222]:
s3.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

Log and Exponents

In [226]:
np.exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

round/ floor ceil

1 round
the numpy.round() function round the element of an array to the nearest or to the specified numbeer of decimalsm

In [229]:
# round to the nearest integer
arr = np.array([1.2, 2.7, 3.5,4.9])
rounded_arr = np.round(arr)
print(rounded_arr)  # it will round the value to nearest integer

[1. 3. 4. 5.]


In [ ]:
# round to two decimal
arr = np.array([1.234,2.567,3.891])
roundedarr = np.round(arr, decimals=1)  # decimal s=1 meands it take one decimal
print(roundedarr)   # it will rounded the value to the nearest two decimal

[1.2 2.6 3.9]


In [236]:
arr = np.array([1.234,3.345,5.345])
round = np.round(arr, decimals=2) # decimal s = 2 means it take two decimal
print(round)

[1.23 3.34 5.34]


In [ ]:
# randomly
np.round(np.random.random((2,3))*100)


array([[24.13131941, 84.66587202,  4.08989625],
       [12.83045197, 97.17878953, 77.37607439]])

In [271]:
b = np.random.random((5,8))

In [272]:
b

array([[0.68873712, 0.6378184 , 0.31218006, 0.11897612, 0.71175637,
        0.31090269, 0.85098689, 0.53568053],
       [0.2295516 , 0.37422847, 0.43789998, 0.48027677, 0.46664086,
        0.23961845, 0.286993  , 0.67763759],
       [0.17180289, 0.81101674, 0.2545022 , 0.84416526, 0.42790883,
        0.34558848, 0.360167  , 0.97672738],
       [0.70500988, 0.89840077, 0.07010788, 0.03706732, 0.8838146 ,
        0.46969   , 0.57739302, 0.22143649],
       [0.88128796, 0.82298929, 0.60717881, 0.09239427, 0.99109859,
        0.77122221, 0.16299546, 0.33270953]])

In [273]:
b*100

array([[68.87371221, 63.78183958, 31.21800564, 11.89761197, 71.17563705,
        31.09026931, 85.09868859, 53.568053  ],
       [22.95516025, 37.42284733, 43.78999784, 48.027677  , 46.6640864 ,
        23.96184532, 28.69929974, 67.76375924],
       [17.18028922, 81.10167443, 25.45021975, 84.4165262 , 42.79088296,
        34.55884763, 36.01670039, 97.67273754],
       [70.50098753, 89.84007722,  7.01078778,  3.70673241, 88.38146007,
        46.96900024, 57.73930161, 22.14364948],
       [88.12879631, 82.29892914, 60.71788097,  9.23942721, 99.10985944,
        77.12222116, 16.29954593, 33.27095267]])

2. Floor

The numpy.floor function returns the largest integer less than or equal to each elementof an array

In [283]:
# Floor operation
arr = np.array([1.2,2.4,3.6,4.8])  # floor oprator generates lees value ex ample 3.4 = 3 and 3.9 = 3
floor_arr = np.floor(arr)
print(floor_arr)

[1. 2. 3. 4.]


In [289]:
np.floor(np.random.random((2,3))*100)

array([[38., 27., 54.],
       [95., 26., 14.]])

Ceil

the numpy.ceil() dunction returns the smallest integer greater than or equal to each element if an array

In [ ]:
arr = np.array([1.2,3.1,4.1,5.1])
ceiled_arr = np.ceil(arr)  # ceil fun genrate big number like 4.1= 5 5.1=6
print(ceiled_arr)

[2. 4. 5. 6.]


In [294]:
np.ceil(np.random.random((2,3))*100)

array([[69., 40., 26.],
       [47., 45., 90.]])

Inexing and Slicng

In [295]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [296]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [297]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [298]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Indexing on 1D array

In [299]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
p1[-1]

np.int64(9)

In [301]:
p1[0]

np.int64(0)

Indexing on 2D array

In [302]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
p2[1,2]  # 1 rows  2 columns and shaping of indexing

np.int64(6)

In [306]:
p2[2,3]  # 2 rows 3 columns and shapping of indexing

np.int64(11)

In [ ]:
p2[1,0]  #1 row 0 columns and shapping of indexing

np.int64(4)

Indexing on 3D (tensor)

In [309]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [308]:
p3[1,0,1]

np.int64(5)