#

In [79]:
A = [1,2,3,4,5,6]

In [80]:
print(A[5])

6


In [81]:
print(A[-2])

5


In [82]:
A


[1, 2, 3, 4, 5, 6]

In [83]:
A[2]=25

In [84]:
A

[1, 2, 25, 4, 5, 6]

In [85]:
A

[1, 2, 25, 4, 5, 6]

In [86]:
A[2]=3

In [87]:
A

[1, 2, 3, 4, 5, 6]

In [88]:
A


[1, 2, 3, 4, 5, 6]

In [89]:
A.append(7)
A

[1, 2, 3, 4, 5, 6, 7]

In [90]:
A

[1, 2, 3, 4, 5, 6, 7]

In [91]:
A.insert(2,10)
A

[1, 2, 10, 3, 4, 5, 6, 7]

In [92]:
A

[1, 2, 10, 3, 4, 5, 6, 7]

In [93]:
A.extend([30,40,50])
A

[1, 2, 10, 3, 4, 5, 6, 7, 30, 40, 50]

In [94]:
A.remove(30)

In [95]:
A

[1, 2, 10, 3, 4, 5, 6, 7, 40, 50]

In [96]:
A.clear()
A

[]

In [97]:
A =[100,200]


In [98]:
max(A)

200

In [99]:
len(A)

2

In [100]:
A = A.pop(1)
A
  

200

In [101]:
a = [1,2,3,4,5]

In [102]:
a.pop(2)

3

In [103]:
a

[1, 2, 4, 5]

In [104]:
a.index(2)

1

In [105]:
a.count(2)

1

In [106]:
a = [6,4,5,7,8,9,1,2]

In [107]:
a.sort()
a

[1, 2, 4, 5, 6, 7, 8, 9]

In [108]:
a.reverse()

In [109]:
a


[9, 8, 7, 6, 5, 4, 2, 1]

In [110]:
a.copy()

[9, 8, 7, 6, 5, 4, 2, 1]

In [111]:
a.clear()

# tuple

In [112]:
t = (0,1,2,3,4,5,6,7,8)
t

(0, 1, 2, 3, 4, 5, 6, 7, 8)

In [113]:
t.count(2)

1

In [114]:
t.index(4)

4

In [115]:
len(t)

9

In [116]:
print(2 in t)

True


In [117]:
print(30 in t)

False


In [118]:
max(t)

8

In [119]:
print(min(t))

0


In [120]:
print(sum(t))

36


In [121]:
print(sorted(t))

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [122]:
print(t[::-1])

(8, 7, 6, 5, 4, 3, 2, 1, 0)


In [123]:
print(tuple(reversed(t)))

(8, 7, 6, 5, 4, 3, 2, 1, 0)


In [124]:
t

(0, 1, 2, 3, 4, 5, 6, 7, 8)

In [125]:
print(t[0:6])

(0, 1, 2, 3, 4, 5)


In [126]:
print(t[::3])

(0, 3, 6)


In [127]:
print(t[::2])

(0, 2, 4, 6, 8)


In [128]:
t

(0, 1, 2, 3, 4, 5, 6, 7, 8)

In [129]:
for i in t:
    print(i)

0
1
2
3
4
5
6
7
8


In [130]:
for i in enumerate(t):
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 5)
(6, 6)
(7, 7)
(8, 8)


# sets

In [131]:
s = {1,1,2,2,3,3,4,4,5,5,6,6}   # duplicate element are not allow in set
s

{1, 2, 3, 4, 5, 6}

In [132]:
s1 = {1,'two',3.14,True}     # set can store multiple datatype like (int, str, float, boolen)
s1

{1, 3.14, 'two'}

In [133]:
s1

{1, 3.14, 'two'}

In [134]:
s2 = {1,2,3,4,5,6,7,8}
s2

{1, 2, 3, 4, 5, 6, 7, 8}

In [135]:
s3 = {1,2,3,4,}

In [136]:
s3

{1, 2, 3, 4}

In [137]:
my_set1 = set(('two' , 'three' , 'one' , 'four'))
my_set1

{'four', 'one', 'three', 'two'}

In [138]:
s4

NameError: name 's4' is not defined

In [ ]:
s

In [ ]:
s.add(7)

In [ ]:
s

In [ ]:
s.update([8,9])
s

In [ ]:
s.remove(9)

In [ ]:
s

In [ ]:
s.discard(9)
s

In [ ]:
s

In [ ]:
s.pop()

In [ ]:
s

In [ ]:
s.clear()

In [ ]:
s

In [ ]:
s = {1,2,3,4,5,6}
s

In [ ]:
s.copy()

In [ ]:
s 

In [ ]:
s1 = {2,3,4,5}
s2 = {6,7,8}
s3 = {9,10,11}


In [ ]:
s1.union(s3)

In [ ]:
s1|s2|s3

In [ ]:
s1.union(s2,s3)

In [ ]:
s1

In [ ]:
s1.update([13,14,15])      # use update add multiple item in set 

In [ ]:
s1

In [ ]:
s1.difference_update([13,14,15])

In [ ]:
s1

In [ ]:
s1 = {2,3,4,5}
s2 = {4,5,6,7}
s3 = {6,7,10,11}

In [ ]:
print(s1.intersection(s2))    

In [ ]:
print(s2.intersection(s3))

In [ ]:
print(s1.difference(s2))

In [ ]:
print(s1.difference(s3))

In [ ]:
print(s2.difference(s3))

In [ ]:
print(s1.symmetric_difference(s2))

In [ ]:
s7 = {10,20,30,40,50}
s8 = {20,30,40,50}
s9 = {1,2,3,4}

In [ ]:
print(s7.issuperset(s8))

In [ ]:
print(s8.issubset(s7))

# dic

In [139]:
dict1 = {1 : 'aditya',2 : 'parth'}

In [140]:
dict1

{1: 'aditya', 2: 'parth'}

In [141]:
print(dict1.get(3))

None


In [144]:
dict1

{1: 'aditya', 2: 'parth'}

In [149]:
print(dict1.keys())

dict_keys([1, 2])


In [150]:
print(dict1.values())

dict_values(['aditya', 'parth'])


In [152]:
print(dict1.items())

dict_items([(1, 'aditya'), (2, 'parth')])


In [157]:
d1 = {'name': 'aditya'}
d2 = {'age': 20, 'city' : 'aurangabad'}
d1.update(d2)
print(d1)

{'name': 'aditya', 'age': 20, 'city': 'aurangabad'}


In [158]:
d1

{'name': 'aditya', 'age': 20, 'city': 'aurangabad'}

In [161]:
d1.pop('age')
print(d1)

{'name': 'aditya', 'city': 'aurangabad'}


In [163]:
d1.popitem()

('city', 'aurangabad')

In [164]:
len(d1)

1

In [165]:
d2 = {1: 'aditya', 2: 'praladh'}
len(d2)

2

In [166]:
d2.copy()

{1: 'aditya', 2: 'praladh'}

In [168]:
d2.clear()

In [170]:
for i in range(5):
    print(i)


0
1
2
3
4


In [171]:
for i in range(2,6):
    print(i)


2
3
4
5


In [176]:
for i in range(2,10,3):
    print(i)

2
5
8


In [178]:
for i in range(5,0,-1): 
    print(i)

5
4
3
2
1


In [182]:
import math
print(math.sqrt(256))

16.0


In [183]:
import math as m
print(m.pi)

3.141592653589793


In [184]:
import math
print(math.floor(4.3))
print(math.ceil(4.1))

4
5


# numpy

In [185]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [186]:
import numpy as np

In [187]:
np.__version__

'1.26.4'

In [188]:
# create list
mylist = [0,1,2,3,4,5]
mylist

[0, 1, 2, 3, 4, 5]

In [189]:
type(mylist)

list

In [190]:
arr = np.array(mylist)
arr

array([0, 1, 2, 3, 4, 5])

In [191]:
print(type(arr))
print(type(mylist))

<class 'numpy.ndarray'>
<class 'list'>


In [193]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [198]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [199]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [200]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [201]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [204]:
np.arange(10,30,30,3)

TypeError: Cannot interpret '3' as a data type

In [205]:
np.arange(20,8)

array([], dtype=int32)

In [206]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [207]:
np.arange(-20,8)    # one arument  alwYS < 2nd argumnent

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [208]:
n = np.arange(-20,8)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [209]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [210]:
np.zeros(3)

array([0., 0., 0.])

In [211]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [212]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [217]:
np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [219]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [220]:
nd = np.zeros((5,9),dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

# once fun()

In [222]:
np.ones(3)

array([1., 1., 1.])

In [223]:
np.ones((3),dtype=int)

array([1, 1, 1])

In [225]:
nd1 = np.ones((10,10),dtype = int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [226]:
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [227]:
np.zeros(3)

array([0., 0., 0.])

In [229]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [230]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [231]:
zero= np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [232]:
zero = np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [233]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [234]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [235]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [236]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [237]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [238]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [243]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [244]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [245]:
n


(6, 7)

In [246]:
n1

(6, 8)

In [247]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [248]:
np.ones(3)

array([1., 1., 1.])

In [251]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [252]:
np.ones(4)

array([1., 1., 1., 1.])

In [253]:
n

(6, 7)

In [254]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [256]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [257]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [258]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [260]:
np.ones(2)

array([1., 1.])

In [261]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [263]:
np.ones((6,10),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [264]:
range(5)

range(0, 5)

In [265]:
r = range(5)
r

range(0, 5)

In [266]:
for i in r:
    print(i)

0
1
2
3
4


In [267]:
list(range(5))

[0, 1, 2, 3, 4]

In [268]:
range(1,10)

range(1, 10)

In [270]:
list(range(1,10,3))

[1, 4, 7]

In [271]:
y =list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [272]:
rand(3,2)

NameError: name 'rand' is not defined

In [274]:
np.random.rand(3)

array([0.93312092, 0.54257191, 0.19361141])

In [275]:
np.random.rand(2,4)

array([[0.50443721, 0.51977665, 0.19341077, 0.39705596],
       [0.081507  , 0.97359351, 0.19114038, 0.77500461]])

In [284]:
np.random.randint(2,4)

3

In [295]:
np.random.randint(2,20)

2

In [297]:
np.random.randint(0,1)

0

In [298]:
np.random.randint(10,20,5)

array([16, 18, 11, 11, 15])

In [301]:
np.random.randint(1,6,4)

array([2, 3, 1, 3])

In [302]:
np.random.randint(1)

0

In [303]:
np.random.randint(30,20,10)

ValueError: low >= high

In [304]:
np.random.randint(-30,20,10)

array([ -3, -15,  -3,  18, -27,   6, -10,  -7, -28,  12])

In [ ]:
np.random.randint(5,9)

6